planner_configs:
  RRTConnectkConfigDefault:
    type: geometric::RRTConnect
    range: 0.0
  RRTstarkConfigDefault:
    type: geometric::RRTstar
    range: 0.0
    goal_bias: 0.05
    delay_collision_checking: 1
left_arm:
  planner_configs: [RRTConnectkConfigDefault, RRTstarkConfigDefault]
  longest_valid_segment_fraction: 0.01
right_arm:
  planner_configs: [RRTConnectkConfigDefault, RRTstarkConfigDefault]
  longest_valid_segment_fraction: 0.01
dual_arms:
  planner_configs: [RRTConnectkConfigDefault, RRTstarkConfigDefault]
  longest_valid_segment_fraction: 0.01
